version: '3'

services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/var/www/symfony
    environment:
      DATABASE_URL: "pgsql://user:password@postgres:5432/test?serverVersion=13&charset=utf8"

  nginx:
    image: nginx:alpine
    ports:
      - "8081:81"
    volumes:
      - .:/var/www/symfony
      - ./nginx/symfony.conf:/etc/nginx/conf.d/default.conf

  postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: test
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
